services:
  - type: web
    name: ajinkya-saivar-api
    runtime: node
    rootDir: server
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        generateValue: false
      - key: GMAIL_USER
        sync: false
      - key: GMAIL_PASS
        sync: false
      - key: MONGODB_URI
        sync: false          # set manually in Render dashboard
      - key: FRONTEND_URL
        sync: false          # set manually in Render dashboard
